name: PR Preview (to gh-pages/pr-preview)
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        if: github.event.action != 'closed'
        with:
          node-version: 22
          cache: 'npm'
      - name: Install & Build
        if: github.event.action != 'closed'
        run: |
          npm ci
          npm run build
      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: dist
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
